root = "."

[build]
    include_ext = ["go", "templ"]
    exclude_dir = ["static"]
    exclude_regex = [".*_templ.go"]
    cmd = "templ generate & go build -o ./tmp/out ./cmd"
    bin = "./tmp/out"
[log]
    time = true